services:
  astrofolio:
    image: aminnausin/astrofolio:latest
    container_name: astrofolio
    restart: unless-stopped
    ports: 
      - 7732:7732
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-astrofolio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --interval 30 --cleanup
    restart: unless-stopped

networks:
  default:
    name: proxy-network
    external: true
