name: CI & Docker Release

on:
  push:
    branches: [ 'main', 'prod' ]

jobs: 
  astro-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------- Node Setup ----------
    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install node dependencies
      run: npm ci

    # ---------- Build Frontend ----------
    - name: Type Check Astro and Build
      run: npm run type-check && npm run build

  # ==========================
  #  Publish Docker Image
  # ==========================
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ astro-tests ]
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          aminnausin/astrofolio:latest
        build-args: |
          DOMAIN=${{ vars.DOMAIN }}
          PLAUSIBLE_DOMAIN=${{ vars.PLAUSIBLE_DOMAIN }}
          RESUME_URL=${{ vars.RESUME_URL }}
 